- requirements.txt
The dataclasses package in the requirements.txt is a backport of Python 3.7's dataclasses module for Python 3.6. 
As a result, it's only available for install when Python3.6 is used.
This PR adds an [environment marker](https://www.python.org/dev/peps/pep-0508/#environment-markers) to the requirements.txt so that people using Python3.7 won't see their `pip install -r requirements.txt` fail.
> Do not install dataclasses if already available

- substratest/assets.py
- substratest/factory.py
- tests/test_execution.py
- tests/test_execution_compute_plan.py
See [Chaincode PR](https://github.com/SubstraFoundation/substra-chaincode/pull/2)
--
This PR bundles several changes:
1. **Fix**: The `traintuple_id` parameter in the `ComputePlanTesttupleSpec`
2. **Refactor**: Create the `INVALID_ALGO_SCRIPT` constant, so that it can be reused accross tests
3. **Refactor**: Move the existing compute plan test to a new file `test_execution_compute_plan.py`
4. **Add new tests**: 
- Compute plan success (single node)
- Compute plan failure (single node)
Note that these new tests each take about 10 seconds to run on my machine. So this increases the total test run time (`make test`) by ~20 secs.
> add 2 compute plan tests: success + recursive fail

- README.md
- substratest/factory.py
As substra-tools is now on docker hub we don't need to pull it manually anymore !
> Remove manual docker pull of substra-tools and update image name

- local-values.yaml
Local shared path was not well set in case of docker-compose setup.
@GuillaumeCisco Can you tell me if this modification will be an issue in the case of a local setup ? I don't think so as the backend in local setup will have access to `${SUBSTRA_PATH}/servermedias` !
> Fix local shared path in docker-compose context.

- substratest/factory.py
The commands related to the workdir are not needed and should then be removed from the test Dockerfiles.
> simplify dockerfiles

- substratest/factory.py
- tests/test_permissions.py
Less hardcoded strings, less errors :)
> spec: Permissions should also be a spec object

- substratest/client.py
- tests/conftest.py
- tests/test_execution.py
- tests/test_execution_compute_plan.py
Since all execution tests rely on a very similar setup, we can use the existing (but dormant) `data_network` fixture so that base assets (datasets, data samples and objectives) are created only once.
> Use data_network for execution tests

- substratest/assets.py
- substratest/client.py
- substratest/factory.py
- tests/test_execution_compute_plan.py
Add 2 tests for generic compute plans:
* make sure circular dependencies are handled correctly
* duplicate the `test_aggregate_composite_traintuples` in a compute plan
This required to update `factory.py` quite a bit.
> Generic compute plan

- substratest/assets.py
- tests/test_execution_compute_plan.py
- do not redefined `_FutureMixin.attach()`, already implemented in parent
class
- `_FutureMixin`: raise a proper error if the asset has not been attached when using the session
- `ComputePlan.list_<tuple>`: use session set from the `_FutureMixin.attach` class method: 
- `ComputePlan.list_<tuple>`: add assert to ensure the list methods are working as expected
- test_compute_plan: small fix regarding typo in state attributes
> Asset ComputePlan: various improvements

- substratest/assets.py
- tests/test_execution_compute_plan.py
Re enabled the compute plan test. It was skipped due to random MVCC read conflict that are fixed in the backend (https://github.com/SubstraFoundation/substra-backend/pull/71)
> enable skip test due to mvcc conflict

- substratest/assets.py
- tests/test_execution.py
- tests/test_execution_compute_plan.py
- tests/test_permissions.py
As specified in the related issue, it is better to use global variables or custom type for this status. It improves code readability, code maintainability and is less error prone.
🔗 Related issue: #29
> Avoid using strings to define tuple status

- substratest/assets.py
- tests/test_execution_compute_plan.py
Fix #42 
Random failure due to random ordering of tuples with the same rank.
Thanks @jmorel for the investigation!
> Fix compute plan test

- README.md
- tests/settings.py
This mode is unused and it doesn't make sense to maintain it.
It's gonna be harder to support it when the network configuration will be more complex.
> Remove parsing of skaffold file

- tests/test_execution_compute_plan.py
This may not be the best solution to test the different behaviour when cancelling a compute plan.
But this will stop the random failures as a quick term solution.
> fix random failures on cancel test

- tests/test_execution.py
It will allow to have a test running a traintuple on each node of the network.
This is closer to a real use case example.
Also checks that we cannot add twice the same tuple (this check is done in the populate).
> Update federated learning test

- tests/test_permissions.py
- this buggy as it requires 3 nodes to be be executed, as a result it has not been launched for a while
- update flake8 as well
> update buggy test

- local-values.yaml
- tests/settings.py
- tests/test_execution.py
- tests/test_network.py
- tests/test_permissions.py
- values.yaml
In this PR:
- fix `test_merge_permissions_denied_process ` that is executed only on envs with at least 3 nodes and that hadn't been updated to reflect API changes
- update `celery_task_max_retry` option in `values.yaml`: rename it as `celery_task_max_retries` and make its value the same as the `CELERY_TASK_MAX_RETRIES` option in the backend
- disable shared path test on remote env with no shared path
- make `test_execution_retry_on_fail` work no matter what the `celery_task_max_retries` value is.
> Fix tests that were broken with non local envs

- Makefile
- README.md
- tests/conftest.py
- tests/test_execution.py
- tests/test_execution_compute_plan.py
- tests/test_permissions.py
Fixes #41 
Creates a new "slow" marker for tests and adds a new `fast-test` target in Makefile that will only run "fast" tests.
With the current tests marked as slow, `make test` runs in 184s for 71 tests while `make fast-test` runs in 48s for 59 tests.
> Add a fast mode for tests

- substratest/client.py
- substratest/factory.py
- tests/test_network.py
Add more tests to cover link between dataset and objective
Companion PRs:
- [substra](https://github.com/SubstraFoundation/substra/pull/94)
- [backend](https://github.com/SubstraFoundation/substra-backend/pull/133)
> Fix: dataset can be linked with only one objective

- requirements.txt
- substratest/assets.py
🔗 Related issue: #37 
This PR aims to add a **data-type validation** on substra-tests in order to be able to check the type of data returned by the [backend](http://github.com/SubstraFoundation/substra-backend) and to return an error is the type received is not the one expected.
We needed to find a library for this.
Some ideas of libraries have been explored:
• [Marshmallow](https://github.com/marshmallow-code/marshmallow)
• [Pydantic](https://github.com/samuelcolvin/pydantic) 
• [MYPY](https://github.com/python/mypy)
We tried to use Marshmallow first, but its wasn't compatible with how substra-tests is made. Indeed, the class instantiation wasn't what we expected and didn't work.
MYPY can be used, but not as a data-type validation tool as we wanted.
So we decided to use **Pydantic** …
> Add data-type validation with Pydantic

- README.md
- substratest/assets.py
- substratest/utils.py
1. make asset loader py36 compatible:
The asset loader method was too complicated. Using private fields was not a good idea and should not be done.
The proposed solution is less flexible but easier to read, understand and to maintain.
Applying a set of fixed rules to rename the assets fields should not be issue. We expect the number of rules to decrease over time (and not the opposite!).
2. asset: remove openerHash to key mapper
3. asset: remove hash to key mapper
Close #78
> Fix asset loader (and restore py36 compatibility)

- substratest/client.py
- tests/conftest.py
- tests/test_execution.py
- tests/test_execution_compute_plan.py
🔗 **Related issue:** #76 
Currently each session has its own state which contains the assets created (and owned) by the session during the current test run.
The objective of the session is to contain all assets necessary for the execution of a test. For example, the fixture global_execution_env returns sessions which contain all necessary assets to run test_aggregatetuple
In order to better reflect this, we'd like to separate the session object into 2 independent object:
- Client (replaces Session) is a wrapper around substra.Client to handle serialization
- State is an independent object with private properties (state._dataset) and public methods to access assets owned by a given node (state.get_dataset(node_id))
Fixtures such as global_execution_env would then not return a factory and a …
> Split session object into client and state

- Makefile
- docker/Dockerfile
- Follow-up to https://github.com/SubstraFoundation/substra-backend/pull/154
- Companion PR: https://github.com/SubstraFoundation/substra/pull/123
```bash
~/code/substra$ make docker
docker build -f docker/Dockerfile . -t substra:latest
Step 1/9 : FROM python:3.7
[...]
Successfully tagged substra:latest
```
Note: You can specify the tag to build: `make docker DOCKER_TAG=my-version`
```bash
~/code/substra-tests$ make docker
docker build -f docker/Dockerfile . -t substra-tests:latest --build-arg SUBSTRA_VERSION=latest
Step 1/10 : ARG SUBSTRA_VERSION=latest
[...]
Successfully tagged substra-tests:latest
```
Note: 
- You can specify the tag to build: `make docker DOCKER_TAG=my-version`
- You can specify the base `substra` image tag to use: `make docker DOCKER_TAG_SUBSTRA=my-version`
```bash
$ …
```
> Add Dockerfile

- tests/test_execution_compute_plan.py
This fixes the test `test_compute_plan` following [this chaincode PR](https://github.com/SubstraFoundation/substra-chaincode/pull/102).
`queryComputePlan` never returns any item in `IDToKey`, see [`getOutComputePlan`](https://github.com/SubstraFoundation/substra-chaincode/blob/34e90747562c9b42ebea22f08345a67cd5f2b2a5/chaincode/compute_plan.go#L280).
Alternatively, instead of this PR, we could change the chaincode behavior so that we return the entire set of id-to-key mappings. But then we'd risk hitting the gRPC size limit (which if I understood correctly was the whole point of the chaincode PR!)
> fix cp test

- substratest/__init__.py
- substratest/assets.py
- substratest/client.py
- tests/conftest.py
- tests/test_execution.py
- tests/test_execution_compute_plan.py
- tests/test_network.py
- tests/test_permissions.py
🔗 **This Pull Request is related to the following issue: #76** 
As specified by @jmorel, there is still some work remaining on this point. He suggested the following changes:
> Split session object into client and state (2)

- tests/conftest.py
- tests/test_execution.py
- tests/test_execution_compute_plan.py
- tests/test_network.py
- tests/test_permissions.py
Currently, there are a few lines at the beginning of each test which allows to get the following variables:
• `factory` - *used for the `create_asset` methods*
• `initial_assets` - *initial assets used in the test*
• `network` - *used to get the client(s)*
They are set using this line:
```py
factory, initial_assets, network = global_execution_env
```  
The goal of this PR would be to pass directly these variable into the test, instead of getting them into. It avoids duplicated code and makes it easier to read.
> Pass factory, client & assets directly in arguments

- substratest/factory.py
Enable the creation of testtuples not just from an objective but also through explicit dataset and data samples.
> Allow dataset / data samples in testtuple spec

- substratest/client.py
- substratest/factory.py
Partial fix of #89 
Replaces all uses of dataclasses in our factory with pydantic BaseModels.
This highlighted several issues in the type hints of Spec objects that I fixed as well.
> Convert all dataclasses to pydantic basemodels

- tests/test_data_samples_order.py
Adds a test checking that the relative order of data samples in traintuples is not preserved (yet). 
Since preserving this relative order is something we'll soon want to do, I opted for writing tests that check that the order is preserved and making them as failing.
> Test data samples relative order in traintuples

- ci/cloudbuild/celerybeat.yaml
- ci/cloudbuild/celeryworker.yaml
- ci/cloudbuild/flower.yaml
- ci/cloudbuild/hlf-k8s.yaml
- ci/cloudbuild/substra-backend.yaml
- ci/cloudbuild/substra-tests.yaml
- ci/run-ci.py
- Store docker images in the same gcloud zone as the k8s cluster (`eu`)
- This minimizes the $ cost of network transfers between the container registry and the kubernetes cluster (see [gcloud pricing](https://cloud.google.com/storage/pricing#network-egress))
- Add a `ci-` prefix to generated docker image tags. 
- This makes it explicit that those images were created for the purpose of being run as part of CI script, and they can safely be deleted after the CI run has finished.
﻿
> CI: Use 'eu' container registry

- tests/test_execution.py
- tests/test_system.py
Fixes #87 
This creates a new `test_system.py` module that contains tests for internal features of the platform.
Moved tests:
* test_execution_retry_on_fail
Tests not moved yet (to be debated):
* test_compute_plan_remove_intermediary_model
* test_add_data_sample_located_in_shared_path
* test_traintuple_data_samples_relative_order 
* test_composite_traintuple_data_samples_relative_order
These 4 tests can be seen as both system and non system at the same time, we just need to decide in which category they should go.
@samlesu, since this was you issue what would you like to do for each of these tests?
> Move system tests to a separate module

- ci/run-ci.py
Companion PR: https://github.com/SubstraFoundation/hlf-k8s/pull/45
The skaffold patching is now unnecessary. Actually, we *need* to remove it because having `statusCheckDeadlineSeconds` twice in the `skaffold.yaml` file makes `skaffold deploy` crash 
```
FATA[0000] creating runner: parsing skaffold config: unable to parse YAML: yaml: unmarshal errors:
line 30: key "statusCheckDeadlineSeconds" already set in map 
```
> remove statusCheckDeadlineSeconds patch

- ci/run-ci.py
Add `helm repo add` which is necessary since https://github.com/SubstraFoundation/substra-backend/pull/260.
See also: 
- failed CI run: https://travis-ci.org/github/SubstraFoundation/substra-tests/builds/696261385
- substra doc PR: https://github.com/SubstraFoundation/substra/pull/176
> add `helm add repo bitnami`

- .travis.yml
- ci/run-ci.py
See end-to-end tests failure: ﻿https://travis-ci.org/github/SubstraFoundation/substra-tests/builds/696664654
> CI: fix order of execution of helm init 

- substratest/assets.py
- substratest/factory.py
- tests/test_execution.py
- tests/test_network.py
🔗 **Related PRs:**
- [substra](https://github.com/SubstraFoundation/substra/pull/143)
- [substra-chaincode](https://github.com/SubstraFoundation/substra-chaincode/pull/111)
- [substra-backend](https://github.com/SubstraFoundation/substra-backend/pull/186)
- [substra-frontend (coming soon)](#)
The goal of these PRs is to add a `metadata` field in every asset in order to be able to store information related to this asset. It could be, for instance, a creation_ts, an epoch, a project_name, ...
Update 04/24:
> The following assets are missing in the tests:
> - dataset,
> - aggregatetuple (WIP),
> - compute_plan.
> The issue I currently have is that the metadata field returned by the aggregatetuple tests is set to an empty dict, but I pass:
{"foo": "bar"}
> I need to find a way to get the …
> Add user metadata

- substratest/assets.py
- substratest/factory.py
- tests/test_execution_compute_plan.py
:link: **Related Pull Requests :**
• [substra](https://github.com/SubstraFoundation/substra/pull/189)
• [substra-chaincode](https://github.com/SubstraFoundation/substra-chaincode/pull/121)
• [substra-backend](https://github.com/SubstraFoundation/substra-backend/pull/273)
This PR aims to add a metadata field to the compute plan asset.
> Add metadata to compute plan

- substratest/factory.py
- tests/settings.py
- tests/test_execution.py
- tests/test_execution_compute_plan.py
As discussed with @jmorel here is an alternative implementation for the opener/algo/metrics.
They are meant to 1. have an implementation that is very simple and 2. use interfaces that match the intended usage, in particular:
- `train` returns a model structure
- `predict` calculates `y` based on the input `model` and the input `X` 
Please let me know your thoughts. I'm particularly interested in feedback on the comments,
I compared the time it takes to run `make test` between:
- `master`
- `improved_asset_code`
- `improved_asset_code_v2`
I ran `make test` 10x on each branch. Both `improved_asset_code` and `improved_asset_code_v2` take longer to run, but the increase is very small.
(those numbers are not worth much, it's just to get a general idea of the size of the increase)
In a future …
> Improved asset code (with realistic interfaces)

- tests/test_execution.py
- tests/test_execution_compute_plan.py
In the tests, one common assertion is on the final performance of the testtuple:
`assert testtuple.dataset.perf == 0.2`
These tests fail at least with the local backend because of float precision:
`assert 0.20000000000000018 == 0.2`
The proposition is to replace all `assert testtuple.dataset.perf == x` with `assert math.isclose(testtuple.dataset.perf, x)`
> Tests on testtuple perf: replace equality test between float by isclose

- .travis.yml
- ci/run-ci.py
- tests/test_network.py
Separate the CI on the remote and local backend:
- the tests on the remote are run with a deployed substra platform
- the tests on the local are run with only substra-tests and substra installed
Skip a test:
- skip the "shared paths" test on the local backend
> Separate CI for the tests on the remote and local backend

- .travis.yml
We currently retry run-ci.py in case it fails the first time. This strategy was put in place because the deployment used to randomly fail (PVC not bound). 
However:
- we haven't seen this PVC issue in a while, so we can presume it's fixed
- the newest change to substra-backend (k8s tasks) significantly increase the run time of run-ci.py. The time limit for a Travis job is 50 min﻿, which is not enough time for two full runs of run-ci.py. As a result, if run-ci.py fails the first time then`run-ci.py` is retried, but we hit the 50 min mark and the build is marked as 'errored'.
This PR removes the retry so that if run-ci.py fails, the build is marked as failed without retrying.
> CI: Don't retry run-ci.py

- .travis.yml
- substratest/client.py
- substratest/factory.py
- tests/conftest.py
- tests/test_debug.py
- tests/test_execution.py
- Update substra-tests to add tests on the debug mode (following the changes in Substra: https://github.com/SubstraFoundation/substra/pull/206)
- Make it easier to debug failures in performance assert: 
- add print statements in the assets (these will be part of the execution logs in the local backend)
- print the execution logs in the tests (not shown in case of success)
- Fixed the CI: upgrade Docker to version 19
- I fixed the versions of docker-ce, docker-ce-cli, containerd, **do we want to always use the latest stable version instead ?**
Need this PR to be merged: https://github.com/SubstraFoundation/substra-tools/pull/42 and to update the substra-tools image
> Update with the hybrid debugging

- Makefile
- charts/substra-tests/templates/deployment.yaml
Exposing the docker socket to the pod does not work because then we do not have permission to mount the volumes in RW on the Docker container
So this is the Docker in Docker method
Source: article on Medium https://medium.com/hootsuite-engineering/building-docker-images-inside-kubernetes-42c6af855f25
They recommend the 'Docker-in-Docker' solution, however when going to the official docker hub https://hub.docker.com/_/docker, they recommend this blog post: https://jpetazzo.github.io/2015/09/03/do-not-use-docker-in-docker-for-ci/ that basically recommends the 'exposing socket' solution so I went with it, as it does not seem so bad and is certainly simpler.
I cannot test the solution for the moment, need either to launch the job manually from the CI or get the credentials to run ci/run_ci.py …
> fix: Docker in Docker solution to use Docker in the debug mode

- tests/test_debug.py
Deactivate test_debug until we can fix them.  
Full logs attached
Checked, did not reproduce on my computer with Python 3.6, 3.7 or 3.8 but @AurelienGasser reproduced (Python 3.8).  
I got the error if I run 'skaffold run' in susbtra-tests then launch the remote tests with `kubectl exec .... -- make test-remote` (same command as in run_ci.py)
[logs.txt](https://github.com/SubstraFoundation/substra-tests/files/5075701/logs.txt)
> deactivate faulty tests

- tests/test_execution_compute_plan.py
Note: this is currently failing against master.
> Check that permissions are correctly set for composite traintuples in CP

- substratest/assets.py
The goal of this multi-repo PRs is to make sure that all the asset creation endpoints returns only the "key" of the asset. 
Indeed, currently `create` and 'get' an asset return, respectively, `pkhash` and `key`. As `pkhash` is only a substra-backend concept, we need to move from `pkhash` to `key` when dealing with substra cli/sdk and frontend.
Consequently, when client create a new asset, the substra-backend will now only return the `key` of the created asset.
There is an exception for compute plan which need to be returned in its complete form because client need to get the ID_to_key mapping and it’s returned only when client create this asset.
The client will take care of doing an extra GET in order to retrieve the complete asset.
PRs : …
> Use key instead of pkhash

- .travis.yml
- ci/run-ci.py
- skaffold.yaml
As we will only support Helm3 in the future the e2e test pipeline should use Helm3 to deploy the substra components in Kubernetes.
This PR should be merged only after these two PRs:
- https://github.com/SubstraFoundation/hlf-k8s/pull/82
- https://github.com/SubstraFoundation/substra-backend/pull/295
> Switch from Helm2 to Helm3

- substratest/assets.py
- substratest/utils.py
The backend responses should be more consistent. The goal of this PR is to make sure that all inputs fields and response fields of backend endpoints are in snake_case format.
PRs:
https://github.com/SubstraFoundation/substra-backend/pull/315
https://github.com/SubstraFoundation/substra/pull/222
https://github.com/SubstraFoundation/substra-tests/pull/142
> Switch from camel case to snake case

- ci/run-ci.py
On a fresh setup (`kubectl` not configured) the CI script should not crash.
> ci: fix crash when current context is null

- ci/run-ci.py
The deadline has been increased in the backend: https://github.com/SubstraFoundation/substra-backend/pull/325
This override is now unnecessary.
> ci: don't override statusCheckDeadlineSeconds

- ci/cloudbuild/celery.yaml
- ci/run-ci.py
As https://github.com/SubstraFoundation/substra-backend/pull/320 has been merged, we can simplify celery services images to only one.
You can launch the ci with `./ci/run-ci.py --substra-backend simplify-celery-images`
Companion PR
https://github.com/SubstraFoundation/substra-backend/pull/323
> Simplify celery images

- ci/run-ci.py
GKE regularly changes cluster version list compatible as master node.
In this PR, we directly fetch the cluster version from `REGULAR` channel in order to avoid failure from deprecated version value.
https://cloud.google.com/kubernetes-engine/docs/release-notes
> Add fetch cluster version function

- .gitignore
- substratest/factory.py
- tests/test_execution.py
- tests/test_network.py
Companion PRs:
- https://github.com/SubstraFoundation/substra/pull/235
- https://github.com/SubstraFoundation/substra-backend/pull/342
- https://github.com/SubstraFoundation/substra-chaincode/pull/128
**Please see the main PR in substra-backend for a detailed description of the changes:** https://github.com/SubstraFoundation/substra-backend/pull/342
---
The mechanism adding random variations to assets specs is now obsolete (because unnecessary) and has been removed.
> Use random UUIDs for asset keys (instead of content hashes)

- ci/run-ci.py
Save money by deleting `disks` provisioned for PVC: those aren't automatically deleted on cluster deletion.
> ci: delete disks on cluster deletion

- ci/run-ci.py
The substra-tests nightly CI, executing nightly tests triggered by a cron, is failing. From the travis logs, it looks like helm stable repo is missing. Nevertheless, when running the `ci/run-ci.py` manually, we don't see this error.
None
We cannot repro this by running `ci/run-ci.py` which will, strangely, work without any issue :(
Trace of the error can be found here : https://travis-ci.org/github/SubstraFoundation/substra-tests/jobs/744318430#L377-L379
To confirm the fix of this issue we need to merge this PR before and wait for the next travis cron job
> Add missing stable helm repo to run the remote CI

- ci/run-ci.py
It looks like `gcloud` cli response on `compute disks delete` put the light on the need to use `--zone` option to be able to delete disks. I added in the PR the option for `compute disks list` and `compute disks delete` 
None
None
You can repro it by launching `ci/run-ci.py` on master branch.
```shell
+ gcloud compute disks list --format="table(name)" --filter="name~^gke-substra-tests-slyk-pvc-.* AND -users:*" | sed 1d
+ gcloud compute disks delete --quiet gke-substra-tests-slyk-pvc-0423b7bf-74ba-4e98-be89-1ea531a9149f gke-substra-tests-slyk-pvc-07c72a4c-5bb3-4bc3-990d-8e6980e0e906 gke-substra-tests-slyk-pvc-10c0c9e9-5dbb-4268-8089-bb4442ed4cf4 gke-subs
tra-tests-slyk-pvc-18b2097b-a7f0-42ad-8f22-143f246ce91e gke-substra-tests-slyk-pvc-1bc0d4fb-a0c8-49b3-a468-5d3dbc974f49 …
```
> Add zones filtering for gcloud disks list and delete

- ci/run-ci.py
It looks like `gcloud` cli response on `compute disks list/delete` put the light on the need to use `--project` flag to be able to list and delete disks in a Travis job.
I added in the PR the flag for `compute disks list` and `compute disks delete` 
None
None
You can repro it by launching the Travis CI with e2e remote tests on master branch but it's not automatic.
```shell
+ gcloud compute disks delete --zone europe-west4-a --quiet ERROR: (gcloud.compute.disks.list) Some requests did not succeed:  - Required 'compute.disks.list' permission for 'projects/travis-ci-prod-oss-4'
/bin/sh: 1: Syntax error: "(" unexpected
ERROR: Deletion of the GCP disks failed Command '["gcloud compute disks delete --zone europe-west4-a --quiet ERROR: (gcloud.compute.disks.list) Some requests did not succeed: …
```
> Add '--project' flag to avoid project value issue in Travis

- tests/test_execution.py
Debug mode - the aggregate tuple took the head model instead of the trunk model of the in composite traintuple and the test result reflected that
> Update test following bugfix - debug mode - aggregate tuple took the head model 

- ci/run-ci.py
In order to be compatible with https://github.com/SubstraFoundation/hlf-k8s/pull/102 we need to update run-ci.py patch function to handle new chaincode value structure for deployment.
None
https://github.com/SubstraFoundation/hlf-k8s/pull/102
`./ci/run-ci.py --substra-chaincode add-channel-log --substra-backend speed-up-download --substra-tests share-chaincode --hlf-k8s channels-share-chaincode`
```
FATAL: 'image'
ERROR:root:'image'
Traceback (most recent call last):
File "/Users/kmoutet/Substra/substra-tests/./ci/run-ci.py", line 603, in main
deploy_all(configs)
File "/Users/kmoutet/Substra/substra-tests/./ci/run-ci.py", line 482, in deploy_all
deploy(config, wait)
File "/Users/kmoutet/Substra/substra-tests/./ci/run-ci.py", line 487, in deploy
skaffold_file = patch_skaffold_file(config) …
```
> Update run-ci.py with new chaincode structure

- skaffold.yaml
E2E CI tests regularly fail because of substra-tests pod deployment stabilization (see trace).
We increase the value of `statusCheckDeadlineSeconds` from `120s` (default) to `300s`
None
None
Run `python ci/run-ci.py --substra-tests increase-status-check-deadline`
```
Waiting for deployments to stabilize...
- substra-tests:deployment/substra-tests: waiting for rollout to finish: 0 of 1 updated replicas are available...
- substra-tests:deployment/substra-tests: could not stabilize within 2m0s
- substra-tests:deployment/substra-tests failed. Error: could not stabilize within 2m0s.
1/1 deployment(s) failed
FATAL: Command '['cd /home/travis/build/SubstraFoundation/substra-tests/ci/src/3UQlGHmusX/substra-tests && skaffold deploy --kube-context=gke_substra-208412_europe-west4-a_substra-tests-2021 …
```
> Increase substra-tests skaffold status check deadline value

- ci/run-ci.py
Currently, the CI script only support branches as arguments.
This PR prevents the script from crashing when trying to get the digest of a git tag, with commands like:
```
run-ci.py --substra-tests 0.6.0
```
> ci: add hacky support for tag parameters

- .github/workflows/end-to-end.yml
- ci/run-ci.py
Fix CI e2e tests by :
- Adding random id in the CI name as gcp use the 18 first chars to name disks
- Fix warning on list gcp disks
> Fix CI cluster name and filter disks

- ci/run-ci.py
You may have to do a `helm repo rm` on conflicting chart (here owkin :) )
> fix: harmonize chart url by removing  extra '/'

- charts/substra-tests/templates/configmap.yaml
- local-backend-values.yaml
- substratest/client.py
- tests/settings.py
- tests/test_execution.py
- values.yaml
Companion PRs:
- https://github.com/SubstraFoundation/substra/pull/261
- https://github.com/SubstraFoundation/substra-chaincode/pull/141
- https://github.com/SubstraFoundation/substra-backend/pull/395
---
This PR adds new tests for the "export model" feature, and covers the main use-cases:
- proxied/unproxied model export (see substra-backend PR for details)
- model export from model key
- model export from tuple key
> test: add tests for export model feature

- substratest/utils.py
Background: By defaut, zip files include timestamps of the files contained in the archive. As a result, two zip files can be identical in terms of their content, but differ in their checksum because the content timestamps are different.
Remove file timestamps from the zip archive, so that two zip files with the same contents have the same checksum. This can be helpful in local/debug scenarios: in the backend use the algo checksum as the image name, disable image deletion, then run a test => kaniko builds are ran once then skipped.
> chore: ignore timestamps in zipfile

- substratest/client.py
- tests/test_execution_compute_plan.py
Test that a transient output effectively has no address after processing (meaning it was properly deleted) and test that we cannot create a new task that depend on this model as an input.
Sometimes ago I introduced a very basic test for transient outputs that just checked if the flag was set. Since then I made some progress and completed the work on the backend side to disable transient outputs properly. It's now time to test the full pipeline.
This test is simpler than the old `test_compute_plan_remove_intermediary_model` because here we are only checking the generic use case: a task with a transient outputs and not a complete workflow with train/predic/test. 
Running the test against a locally deployed Substra stack.
> test: complete the test for transient outputs

- CHANGELOG.md
- Makefile
- substratest/client.py
- tests/conftest.py
- tests/test_execution.py
- tests/test_hybrid_mode.py
- tests/workflows/README.md
- tests/workflows/mnist-fedavg/assets/aggregate_algo.py
https://github.com/Substra/substra/pull/287 --> contains the description
https://github.com/Substra/substrafl/pull/19
https://github.com/Substra/substra-tests/pull/210
> test: update the tests, Client(execution_mode)

- tests/test_execution.py
Companion PRs:
- https://github.com/Substra/substra-backend/pull/483 (main PR)
- https://github.com/Substra/orchestrator/pull/38
- https://github.com/Substra/substra/pull/295
- https://github.com/Substra/substra-tests/pull/218 (this PR)
- https://github.com/Substra/substra-frontend/pull/116
- https://github.com/Substra/substra-documentation/pull/184
--- 
Previously, only execution errors had logs. Now, build errors have logs too.
> test: add container image build logs tests (docker+remote)

- CHANGELOG.md
- substratest/settings.py
- tests/test_gpu.py
Signed-off-by: Guilhem Barthes <guilhem.barthes@owkin.com>
Update substratools Docker image name to the new one using lastr Ubuntu LTS (22.04) and supporting Python 3.10.
- https://github.com/Substra/substra/pull/316
- https://github.com/Substra/substra-tools/pull/68
- https://github.com/Substra/substrafl/pull/49
- https://github.com/Substra/substra-documentation/pull/222
> refactor: replace substra-tools Docker image name

- substratest/channel.py
- tests/test_synchronized.py
This PR adds a test to verify that creator username is not propagated to other organization and instead replaced by external.
Companion PRs:
- https://github.com/Substra/substra-backend/pull/511
- https://github.com/Substra/substra-frontend/pull/124
- https://github.com/Substra/substra/pull/331
> feat: add test for compute plan creator

- CHANGELOG.md
- substratest/client.py
- tests/conftest.py
- tests/test_data_samples_order.py
- tests/test_execution.py
- tests/test_execution_compute_plan.py
- tests/test_hybrid_mode.py
- tests/workflows/mnist-fedavg/assets/composite_function.py
Performance asset were unique regarding their compute task key, and the function key they were computed from. Or, we want to have the possibility to have a function that outputs several performance and store them in the same task.
This implies two main things:
- Performance are now unique regarding the compute task key, the function key AND the output identifier
- The frontend must serialize regarding the identifier, and not the function key
The PR batch modify both the orchestrator and backend db in order to include the identifier as an additional unique condition.
In the backend, we use the ComputeTaskOutput as primary key directly.
- https://github.com/Substra/substra-backend/pull/634
- https://github.com/Substra/substra-tests/pull/251 (main)
- …
> test: custom metric task with several outputs

- CHANGELOG.md
- substratest/client.py
- tests/test_data_samples_order.py
- tests/test_execution.py
- tests/test_execution_compute_plan.py
- tests/test_hybrid_mode.py
- tests/test_permissions.py
- tests/workflows/mnist-fedavg/test_workflow.py
- https://github.com/Substra/substra-backend/pull/509
- https://github.com/Substra/substra/pull/361
- https://github.com/Substra/substrafl/pull/129
Adapt tests to:
- remove usage of `.value` in task outputs
- use new functions to get input/output assets.
Fixes FL-652
Ci in `substra` companion PR
> feat: use new substra functions

- tests/conftest.py
Fix https://github.com/Substra/substra-tests/pull/257 where a `token` (attribute of `substratest.Client`) was still in use instead of `_token` (already available in `substra.Client`, now mother class of `substratest.Client`)
> fix: use `_token` instead of `token`

- substratest/client.py
PR https://github.com/Substra/substra-tests/pull/257 broke `wait_model_deletion` as a `model =` is missing in the while loop ; currently the `wait_model_deletion` is checking that a model is deleted without never updating the model.
Before PR #257 :
```
def wait_model_deletion(self, model_key):
...
model = self._client.get_model(model_key)
while model.address:
...
time.sleep(self.future_polling_period)
model = self._client.get_model(model_key)
```
After # 257:
```
def wait_model_deletion(self, model_key):
...
model = super().get_model(model_key)
while model.address:
...
time.sleep(self.future_polling_period)
super().get_model(model_key)
```
After this one:
```
def wait_model_deletion(self, model_key):
...
model = super().get_model(model_key)
while model.address:
... …
```
> fix: `wait_model_deletion` didn't update model

- CHANGELOG.md
- Define test client (`substratest.client.Client`) as child class of `substra.Client` (#205)
([#257](https://github.com/Substra/substra-tests/pull/257))
> chore: release 0.42.0

- CHANGELOG.md
- substratest/factory.py
- substratest/fl_interface.py
- tests/test_data_samples_order.py
- tests/test_execution.py
- tests/test_execution_compute_plan.py
- tests/test_gpu.py
- tests/test_hybrid_mode.py
- tests/test_permissions.py
- tests/workflows/mnist-fedavg/assets/aggregate_function.py
- tests/workflows/mnist-fedavg/assets/composite_function.py
Remove models and model to input and output identifier to put only `shared_state`. This change help to improve the flexibility on workflows. In particular, it unlock the possibility to link train tasks with each other (needde in cyclic strategy for instance).
- https://github.com/Substra/substrafl/pull/142 (main)
- https://github.com/Substra/substra/pull/367
- https://github.com/Substra/substra-tools/pull/84
- https://github.com/Substra/substra-tests/pull/261
> chore: remove models and model from input and output identifier

- CHANGELOG.md
- substratest/client.py
- substratest/errors.py
- tests/test_data_samples_order.py
- tests/test_docker_image_build.py
- tests/test_execution.py
- tests/test_execution_compute_plan.py
- tests/test_permissions.py
- tests/test_synchronized.py
- https://github.com/Substra/substra/pull/368
- https://github.com/Substra/substrafl/pull/147
- https://github.com/Substra/substra-tests/pull/263
- https://github.com/Substra/substra-documentation/pull/327
Centralize `wait_task` and `wait_compute_plan`, and re-use the implementation added in `substra` through the other components.
Fixes FL-1052
> chore: centralize wait task in substrasdk

- tests/test_docker_image_build.py
Check that build is launched when function is created, and that they are build in the right order. Part of FL-1147
> feat: add first tests on builder

- CHANGELOG.md
- tests/test_execution_compute_plan.py
- https://github.com/Substra/orchestrator/pull/366
- https://github.com/Substra/substra-backend/pull/823
- https://github.com/Substra/substra/pull/397
- https://github.com/Substra/substra-frontend/pull/297
- https://github.com/Substra/substra-documentation/pull/390
Fixes FL-1397
Tests are failing because the changes on `substra` are not on `main` yet
> feat!: add new compute tasks status linked to function status

- tests/test_network.py
> chore: don't check function status to reduce flakiness

- tests/test_execution.py
- tests/test_permissions.py
> feat: add tests to check cleaning of transient output assets

- changes/363.added
- changes/369.fixed
- tests/test_gpu.py
- tests/workflows/mnist-fedavg/test_workflow.py
Fixes CI following Python 3.12 support.
> chore: bump Pytorch version to 2.2.1 in tests

- changes/383.added
- tests/test_docker_image_build.py
Fixes FL-1659
- https://github.com/Substra/substra-backend/pull/997
> feat: add test for function build cancelation
