README.md
Here are some README suggested changes. 
Please feel free to suggest edits if you think something could be made clearer!
=> Move values files to root of repository (README)

.github/CODEOWNERS
This PR adds the list of codeowners as discussed some time ago with the new orga.
=> add codeowners according to new orga

substratest/assets.py, substratest/client.py, substratest/factory.py, tests/test_execution.py
Missing test using aggregate algo / traintuple
=> Add aggregate algo/traintuple to tests helper

substratest/assets.py, substratest/client.py, substratest/errors.py, substratest/factory.py, tests/test_execution.py, tests/test_execution_compute_plan.py, tests/test_network.py
Associated PRs:
- [cli](https://github.com/SubstraFoundation/substra/pull/5)
- [backend](https://github.com/SubstraFoundation/substra-backend/pull/13)
- [chaincode](https://github.com/SubstraFoundation/substra-chaincode/pull/5)
- [tools](https://github.com/SubstraFoundation/substra-tools/pull/3)
=> Add composite algo and traintuple to tests helper

substratest/client.py, tests/conftest.py
Update the state of the session at each get_*. Only assets that were added during the session are updated.
=> Session state update on get

substratest/assets.py, tests/test_execution_compute_plan.py
=> Fix compute plan filters

substratest/assets.py, substratest/factory.py, tests/test_execution.py, tests/test_execution_compute_plan.py, tests/test_permissions.py
Companion PRs: 
* [backend](https://github.com/SubstraFoundation/substra-backend/pull/63)
* [substra](https://github.com/SubstraFoundation/substra/pull/52)
=> Fail fast: remove evaluation for train like tuples

substratest/factory.py
Require https://github.com/SubstraFoundation/substra-tools/pull/18
=> update substratools default version

substratest/factory.py, tests/conftest.py
This will ensure all created assets in a test run will have a unique name. This could help when listing asset.
=> factory: add tests suite uuid to factory name

substratest/assets.py, substratest/client.py, tests/test_execution.py, tests/test_execution_compute_plan.py, tests/test_permissions.py
Companion PR:
- [substra](https://github.com/SubstraFoundation/substra/pull/56)
- [backend](https://github.com/SubstraFoundation/substra-backend/pull/65)
- [chaincode](https://github.com/SubstraFoundation/substra-chaincode/pull/53)
- [frontend](https://github.com/SubstraFoundation/substra-frontend/pull/33)
=> Cancel compute plan

tests/test_execution_compute_plan.py
related to https://github.com/SubstraFoundation/substra-chaincode/pull/62
=> Do not cancel  already done/failed/doing tuples

README.md
When reviewing, do not hesitate to comment if you disagree with some of the points or to add more points.
=> Add a few words regarding tests design

local-values.yaml, tests/conftest.py, tests/settings.py, tests/test_execution.py, values.yaml
Companion PR: https://github.com/SubstraFoundation/substra-backend/pull/92
=> add test for intermediate model removal

substratest/assets.py, substratest/factory.py, tests/test_execution.py, tests/test_execution_compute_plan.py
Link with https://github.com/SubstraFoundation/substra-chaincode/pull/71 and https://github.com/SubstraFoundation/substra-backend/pull/102
=> Adapt tests to new compute plan

substratest/assets.py, tests/test_network.py
- group tests on all asset types together
=> add tests on get asset error cases

tests/test_permissions.py
NB: the test doesn't pass at the moment, it's waiting for an upcoming fix.
=> Add model permissions check

tests/test_execution_compute_plan.py
A todo in the code requested a new testtuple in the `test_compute_plan` test. Here it is!
=> Fix todo: add testtuple to basic compute plan

substratest/factory.py
Companion PR to https://github.com/SubstraFoundation/substra-tools/pull/24
In order for this PR to be merged, the one in substra-tools will have to be merged first a new release (0.5.0) will have to be done.
=> Remove train predictions

substratest/assets.py
https://github.com/SubstraFoundation/substra-backend/pull/139
https://github.com/SubstraFoundation/substra-chaincode/pull/84
=> Update composite structure

tests/test_permissions.py
PR based on #139
This PR tests the change introduced in https://github.com/SubstraFoundation/substra-chaincode/pull/87
=> prevent composite traintuple creation if worker not the same

substratest/factory.py, tests/test_execution.py
We were only testing the failure behavior for traintuples. This adds tests for aggregatuples and composite traintuples as well.
=> Additional failure tests

substratest/factory.py, tests/test_execution_compute_plan.py
Companion PR : https://github.com/SubstraFoundation/substra-chaincode/pull/106 & https://github.com/SubstraFoundation/substra-backend/pull/172 & https://github.com/SubstraFoundation/substra/pull/135
=> Add cleanModels option

.travis.yml, ci/run-ci.py
Prepare values for merge to master
=> Prepare for merge to master

substratest/client.py, tests/test_network.py
End to end test to validate the following backend PR: https://github.com/SubstraFoundation/substra-backend/pull/239
=> add test to link dataset and datasamples

substratest/factory.py, tests/test_permissions.py, tests/test_system.py
Companion PR https://github.com/SubstraFoundation/substra-backend/pull/188
Remove public key from out composite traintuple specs.
=> Remove public key from trunk model permissions

docker/substra-tests/Dockerfile, substratest/client.py
Companion PR to https://github.com/SubstraFoundation/substra/pull/138
=> Use substra.Client new login method

substratest/client.py, tests/conftest.py, tests/test_system.py
Fix the client instantiation following API changes, following the changes in: https://github.com/SubstraFoundation/substra/pull/177
=> fix client API change

substratest/factory.py
Update substra tests to use the latest version of substra tools (fake methods take n_samples as argument) and generate more realistic output in the factory. This may allow us to test that everything went well in the workflow by asserting that the final performance equals a certain value.
- update the factory opener script, methods fake_X and fake_y take n_samples as argument and their output depends on its value
- update the factory opener script, get_X, get_y and the data sample generator for more realistic outputs
When the https://github.com/SubstraFoundation/substra/pull/195 is merged, it will be possible to use "fake_data" from the sdk so we will be able to test that.
=> Add n_fake_samples and more realistic samples and output to the factory

substratest/factory.py
Companion PR: https://github.com/SubstraFoundation/substra-tools/pull/41
=> Use substratools-minimal

ci/run-ci.py
In the CI case, no context is configured (clean install).
So we need, at least, to check if there are contexts to have a current context.
=> Fix kubectl restore old context if no one is set

tests/test_execution_compute_plan.py
Companion PR to https://github.com/SubstraFoundation/substra/pull/216
=> feat: autobatching

ci/run-ci.py
- Fixed substra-tests image tag: the correct tag was built, but an incorrect tag was deployed
- (minor) Improved logging: display the substra commit SHA alongside the other projects' commit SHA + group git operations
=> fix substra-tests image tag

substratest/client.py
Companion PR: https://github.com/SubstraFoundation/substra/pull/221
We systematically get the full object (not only the key) for the tests.
=> get asset = True for the tests

ci/run-ci.py
Attempt at fixing https://travis-ci.org/github/SubstraFoundation/substra-tests/jobs/726117657 (untested)
=> ci: add missing helm repo

ci/run-ci.py
Companion PR: https://github.com/SubstraFoundation/hlf-k8s/pull/95
Deployment stabilization duration on GKE:
- Without pre-generated secrets: **~6 min**
- With pre-generated secrets: **~2 min**
=> CI: Use pre-generated HLF secrets

ci/run-ci.py
- bump kubernetes version
- changed the default susbtra-tests timeout from 300 (default) to 400 to mitigate "future timeout" errors
- added --machine-type param
- remove warnings at GKE cluster creation
- rename a few params/variables for clarity
﻿
=> CI: Various minor improvements

substratest/client.py, substratest/factory.py, tests/test_data_samples_order.py, tests/test_debug.py, tests/test_execution.py, tests/test_execution_compute_plan.py
Companion PRs:
- https://github.com/SubstraFoundation/substra-backend/pull/345
- https://github.com/SubstraFoundation/substra-chaincode/pull/129
- https://github.com/SubstraFoundation/substra/pull/241
Rename:
| Before | After |
|---|----|
| `compute_plan_id` | `compute_plan_key` (or simply `key`) |
|  `hash` | `checksum` |
| `data_manager.keys` | `data_manager.data_sample_keys` |
=> Rename a few attributes

ci/run-ci.py
=> ci: fix xargs -r unvailabale on macos

ci/run-ci.py, substratest/factory.py, tests/test_data_samples_order.py
⚠️ In order for this PR to be merged, https://github.com/SubstraFoundation/substra-tools/pull/43 and https://github.com/SubstraFoundation/substra-backend/pull/344 will have to be merged first.
Main PR: https://github.com/SubstraFoundation/substra-tools/pull/43
Fixes and activates the tests on data samples order.
=> Data samples order

ci/cloudbuild/hlf-k8s.yaml, ci/cloudbuild/substra-backend.yaml, ci/cloudbuild/substra-chaincode.yaml, ci/cloudbuild/substra-tests.yaml
Update kaniko executor version to the last one :)
=> Update kaniko executor version

ci/run-ci.py
=> Fix remove gcloud disk pattern

.github/workflows/end-to-end.yml
Bump the skaffold version to `v1.20.0`.
This change is done to be compatible with the latest [hlf-k8s](https://github.com/SubstraFoundation/hlf-k8s) `skaffold.yaml` file that uses the `skaffold/v2beta12` API. 
I tested the updated curl manually.
```sh
curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/v1.20.0/skaffold-linux-amd64
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100 50.1M  100 50.1M    0     0  28.6M      0  0:00:01  0:00:01 --:--:-- 28.6M
```
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
=> Bump skaffold

README.md, substratest/factory.py, tests/test_data_samples_order.py
Merge https://github.com/SubstraFoundation/substra/pull/259 first.
=> Adding test to check if the order in the substra objective is the same as the order in algo.predict()

tests/test_permissions.py
Companion PR: https://github.com/SubstraFoundation/substra-chaincode/pull/139
=> Add model permission tests

tests/test_data_samples_order.py
Fix issue in datasamples order tests
Update objective specification which need to have test-only datasamples
Update testtuple specification to be more specific on sample used (different of the train)
Companion PR https://github.com/SubstraFoundation/substra-chaincode/pull/140
=> fix: Update objective specification and remove shuffling in datasample order tests

tests/test_execution_compute_plan.py
Until now, we didn't have tests for the "local folder" feature﻿.
=> test: add local folder test

tests/test_execution_compute_plan.py
This field is being deprecated, let's not use it.
Companion PR for https://github.com/Substra/substra/pull/288
=> feat: remove Model.category

substratest/factory.py, substratest/settings.py, tests/test_data_samples_order.py, tests/workflows/mnist-fedavg/assets/metrics.py
https://github.com/Substra/substra-tools/pull/60
=> feat: update following the metric change in substratools

CHANGELOG.md
=> chore: release 0.34.0

CHANGELOG.md, substratest/factory.py, substratest/fl_interface.py, tests/conftest.py, tests/test_data_samples_order.py, tests/test_docker_image_build.py, tests/test_execution.py, tests/test_execution_compute_plan.py, tests/test_hybrid_mode.py, tests/workflows/mnist-fedavg/test_workflow.py
Companion PRs:
substra-tests: https://github.com/Substra/substra-tests/pull/219 (here)
substrafl: https://github.com/Substra/substrafl/pull/29
substra: https://github.com/Substra/substra/pull/294 (main)
documentation: https://github.com/Substra/substra-documentation/pull/186
orchestrator: https://github.com/Substra/orchestrator/pull/42
backend: https://github.com/Substra/substra-backend/pull/487
=> refactor: algo category from AlgoSpec

CHANGELOG.md
Signed-off-by: Serge Bouchut <serge.bouchut@owkin.com>
=> chore: release 0.35.0

CHANGELOG.md, substratest/assets.py, substratest/client.py, substratest/factory.py, tests/conftest.py, tests/test_data_samples_order.py, tests/test_docker_image_build.py, tests/test_execution.py, tests/test_execution_compute_plan.py, tests/test_gpu.py, tests/test_hybrid_mode.py, tests/test_permissions.py, tests/test_synchronized.py, tests/workflows/mnist-fedavg/test_workflow.py
https://github.com/Substra/substra-backend/pull/476
https://github.com/Substra/substrafl/pull/31
https://github.com/Substra/substra/pull/299
=> feat: use generic task

CHANGELOG.md, substratest/factory.py, substratest/settings.py, tests/test_data_samples_order.py, tests/test_docker_image_build.py, tests/test_execution.py, tests/test_execution_compute_plan.py, tests/test_gpu.py, tests/test_permissions.py, tests/workflows/mnist-fedavg/assets/aggregate_algo.py, tests/workflows/mnist-fedavg/assets/composite_algo.py, tests/workflows/mnist-fedavg/assets/metrics.py, tests/workflows/mnist-fedavg/test_workflow.py
Companion PR:
- MAIN: https://github.com/Substra/substra-tools/pull/63
- https://github.com/Substra/substra/pull/303
- https://github.com/Substra/substrafl/pull/34
- https://github.com/Substra/substra-documentation/pull/201
- https://github.com/Substra/substra-tests/pull/224
=> feat: algo to function in substratools

.github/CODEOWNERS, CHANGELOG.md
=> chore: update code owners

.github/workflows/python.yml, CHANGELOG.md, docker/substra-tests/Dockerfile
- https://github.com/Substra/substra-tests/pull/232
- https://github.com/owkin/substra-ci/pull/89
- https://github.com/Substra/substrafl/pull/56
- https://github.com/owkin/substra-ci/actions/runs/3534248205
=> feat: add python 3.10 support

CHANGELOG.md
=> chore: release 0.37.0

CHANGELOG.md
=> chore: release 0.38.0

CHANGELOG.md, README.md, substratest/client.py, substratest/factory.py, substratest/fl_interface.py, tests/test_data_samples_order.py, tests/test_docker_image_build.py, tests/test_execution.py, tests/test_execution_compute_plan.py, tests/test_gpu.py, tests/test_hybrid_mode.py, tests/test_permissions.py, tests/test_synchronized.py, tests/workflows/mnist-fedavg/test_workflow.py
https://app.asana.com/0/1203124674173179/1203842723899063/f
- https://github.com/Substra/substra-tests/pull/239
- https://github.com/Substra/substra/pull/337
- https://github.com/Substra/substrafl/pull/79
- https://github.com/owkin/substra-ci/actions/runs/4044324704
=> chore: rename tuple to task

CHANGELOG.md
- Minor dependency updates. See commit history for more details.
=> chore: release 0.44.0

CHANGELOG.md, requirements.txt, substratest/channel.py, substratest/client.py, substratest/factory.py, substratest/settings.py, tests/conftest.py, tests/test_execution.py, tests/test_execution_compute_plan.py, tests/test_filters.py, tests/workflows/mnist-fedavg/test_workflow.py
- https://github.com/Substra/substra/pull/375 (main)
- https://github.com/Substra/substrafl/pull/159
- https://github.com/Substra/substra-tests/pull/272
- https://github.com/Substra/substra-backend/pull/718
=> chore: bump to pydantic 2.3.0

.github/workflows/python.yml, CHANGELOG.md, docker/substra-tests/Dockerfile, requirements-workflows.txt, skaffold.yaml, substratest/factory.py, tests/test_data_samples_order.py, tests/test_execution.py, tests/test_gpu.py, tests/workflows/mnist-fedavg/test_workflow.py
- https://github.com/Substra/substra-tools/pull/85 (main)
- https://github.com/Substra/substrafl/pull/169
- https://github.com/Substra/substra/pull/388
- https://github.com/Substra/substra-tests/pull/283
- https://github.com/Substra/substra-documentation/pull/367
- https://github.com/owkin/substra-ci/pull/127
- https://github.com/owkin/substra-generator/pull/136
=> chore: add python 3.11 support

tests/test_execution.py, tests/test_execution_compute_plan.py, tests/test_hybrid_mode.py
=> chore: unskip tests

CHANGELOG.md
=> chore: release `0.48.0`

CHANGELOG.md, tests/test_execution_compute_plan.py
=> feat: update ComputePlan statuses

substratest/factory.py
- https://github.com/Substra/substra/pull/405 (main)
- https://github.com/Substra/substra-documentation/pull/412
- https://github.com/Substra/substrafl/pull/202
- https://github.com/Substra/substra-backend/pull/860
- https://github.com/Substra/substra-tests/pull/337
- https://github.com/Substra/orchestrator/pull/394
=> chore: remove type in datasetspec

changes/1517.changed, tests/test_execution_compute_plan.py
=> fix: count execution rundown

tests/workflows/mnist-fedavg/test_workflow.py
=> fix: MNIST workflow

changes/391.changed, requirements-workflows.txt
=> chore: upgrade dependencies
